### ISSUE TITLE
Candlestick in sample report not showing

### ISSUE THREAD

**Issue by rtong0130** [okviz/Candlestick#5]
Hi, I'm trying to use the candlestick visualization but when I open the sample report from the okviz website, the candlestick chart is blank.  I'm running Power BI Desktop Version: 2.48.4792.721 64-bit (July, 2017) and the candlestick version that's in the sample report pbix.  Screenshot of what I see when I open the file below.  Is there something else I need to do to have the graph populate?  Greatly appreciate the help!

![candlestick capture](https://user-images.githubusercontent.com/25043785/39683941-2db4d048-517e-11e8-8bf0-f8e57991eac7.JPG)

**Comment by danieleperilli** [comment]
You must update Power BI to the March 2018 version or to a newer one.
